parameters:
  - name: stepName
    type: string

  - name: artifactName
    type: string

  - name: targetPath
    type: string

  - name: specificArtifact
    type: boolean
    default: false

  - name: runId
    type: string
    default: ''

steps:
  - script: |
      echo $(System.TeamProject)
    displayName : Test step

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact - Win x64'
    inputs:
      artifactName: ${{ parameters.artifactName}}
      targetPath: '${{ parameters.targetPath }}'
      ${{ if eq(parameters.specificArtifact, false)}}:
        buildType: 'current'
      ${{ else }}:
          source: 'specific'
          project: 'lotus'
          pipeline: $(Build.DefinitionName)
          runVersion: 'specific'
          runId: ${{ parameters.runId }}
