jobs:
- template: templates/linux-ci.yml
  parameters:
    AgentPool : 'Linux-Multi-GPU'
    JobName: 'Linux_CI_Multi_GPU_TensorRT_Dev'
    # The latest TensorRT container only supports ubuntu20.04 and python 3.8
    RunDockerBuildArgs: '-o ubuntu20.04 -d tensorrt -x "--enable_multi_device_test --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=52"'
    DoNugetPack:  'false'
    ArtifactName: 'drop-linux'
